from fpdf import FPDF

class Rep(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "Meeting Summary", border= 0, ln= 1, align= "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Generated by SAKSHI LEDGER | Confidential | Page {self.page_no()}", border= 0, ln= 0, align= "C")

def gen_pdf(data_):
    new_= Rep()
    new_.add_page()
    
    new_.set_font("Helvetica", "B", 14)
    new_.cell(0, 10, data_[ "summary" ][ "meeting_title" ], ln= 1)
    
    new_.set_font("Helvetica", "", 11)
    new_.cell(0, 8, f"Date: {data_[ 'summary' ][ 'date' ]}", ln= 1)
    
    att_= ", ".join(data_[ "summary" ][ "attendees" ])
    new_.cell(0, 8, f"Attendees: {att_}", ln= 1)
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Key Metrics", ln= 1)
    new_.set_font("Helvetica", "", 11)
    m_= data_[ "summary" ][ "metrics" ]
    new_.cell(0, 6, f"Duration: {m_[ 'duration_hours' ]} Hours | Attendees: {m_[ 'attendees_count' ]} | Decisions: {m_[ 'decisions_count' ]} | Actions: {m_[ 'actions_count' ]}", ln= 1)
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Executive Summary", ln= 1)
    new_.set_font("Helvetica", "", 11)
    new_.multi_cell(0, 6, data_[ "summary" ][ "executive_summary" ])
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Key Decisions", ln= 1)
    new_.set_font("Helvetica", "", 11)
    for d in data_[ "summary" ][ "key_decisions" ]:
        new_.multi_cell(0, 6, f"- {d}")
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Action Items", ln= 1)
    new_.set_font("Helvetica", "B", 10)
    new_.cell(90, 8, "Task", border= 1)
    new_.cell(50, 8, "Owner", border= 1)
    new_.cell(40, 8, "Deadline", border= 1, ln= 1)
    
    new_.set_font("Helvetica", "", 10)
    for act in data_[ "action_items" ]:
        new_.cell(90, 8, act[ "task" ][ :45 ], border= 1)
        new_.cell(50, 8, act[ "owner" ][ :20 ], border= 1)
        new_.cell(40, 8, act[ "due_date" ][ :15 ], border= 1, ln= 1)
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Key Discussion Points", ln= 1)
    new_.set_font("Helvetica", "", 11)
    for p in data_[ "summary" ][ "key_discussion_points" ]:
        new_.multi_cell(0, 6, f"- {p}")
    new_.ln(5)

    new_.set_font("Helvetica", "B", 12)
    new_.cell(0, 8, "Pending Issues", ln= 1)
    new_.set_font("Helvetica", "", 11)
    for p in data_[ "summary" ][ "pending_issues" ]:
        new_.multi_cell(0, 6, f"- {p}")

    new_.output("SAKSHI_LEDGER_Report.pdf")
    return "SAKSHI_LEDGER_Report.pdf"